config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "links#index"

  namespace :api do
    namespace :v1 do
      resources :links
    end
  end

  resources :links do
    resources :upvotes, only: %i[ create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :url
  validates_uniqueness_of :url

  scope :highest_votes, -> {order(Arel.sql("upvotes - downvotes DESC"))}

  def upvote
    increment!(:upvotes)
  end
end

app/models/score.rb
class Score
  CONTROVERSIAL_THRESHOLD = 0.2

  attr_reader :upvotes, :downvotes

  def initialize(link)
    @upvotes = link.upvotes
    @downvotes = link.downvotes
  end

  def value
    upvotes - downvotes
  end

  def controversial?
    score_delta_percentage < CONTROVERSIAL_THRESHOLD
  end

  private

  def score_delta_percentage
    score_delta.to_f / high_score
  end

  def high_score
    [upvotes, downvotes].max
  end

  def score_delta
    value.abs
  end
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  def index
    links = Link.highest_votes

    render json: links
  end

  def create
    link = Link.new(link_params)

    if link.save
      render json: link, status: :created
    else
      render json: { errors: link.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = Link.highest_votes
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)

    if @link.save
      redirect_to link_path(@link)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update; end

  def destroy; end

  private

    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    @link = Link.find(params[:link_id])
    @link.upvote

    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_score_for(link)
    score = Score.new(link)
    "#{score.value} (+#{score.upvotes}, -#{score.downvotes})"
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_link.html.erb
<li id="<%= dom_id(link) %>">
  <%= button_to "Upvote", link_upvotes_path(link), method: :post %>
  <div data-role="score"><%= formatted_score_for(link) %></div>
  <%= link_to link.title, link.url %>

  <% if link.url.include?("jpg") %>
    <%= image_tag link.url %>

  <% end %>
</li>

app/views/links/index.html.erb
<%= link_to "Submit a new link", new_link_path %>
<ul>
  <%= render @links %>
</ul>

app/views/links/new.html.erb
<%= form_with(
  model: @link
  ) do |form| %>
  <%= render "shared/error_messages", object: @link %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>
  <%= form.submit "Submit!" %>
<% end %>

app/views/links/show.html.erb
<%= link_to @link.title, @link.url %>

<% if @link.url.include?("jpg") %>
  <%= image_tag @link.url %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanition">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>